title = "MigraCode Barcelona"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-theme" 
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/common-content" 
    [[module.imports.mounts]]
      source = "en"
      target = "content"
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-guides" 
    [[module.imports.mounts]]
      source = "content"
      target = "content/guides"
  [[module.imports]]
    path = "github.com/CodeYourFuture/CYF-PD" 
    [[module.imports.mounts]]
      source = "content/blocks"
      target = "content/pd/blocks"

[menus]
    [[menus.secondary]]
        name = "Guides 👈🏾"
        weight = 1
        url = "/guides"
     [[menus.secondary]]
        name = "Join Us 👋🏿"
        weight = 2
        url = "https://migracode.org/volunteer/"
    [[menus.secondary]]
        name = "Support 🫶🏼"
        weight = 3
        url = "https://migracode.org/donate-to-migracode-barcelona/"    

[params]
googleFonts="https://fonts.googleapis.com/css2?family=Jura:wght@300;400;700&display=swap"
description = "A free and open source software development programme."
main_website = "https://migracode.org/"
main_org_name = "MigraCode Barcelona"
our_name="MCB"
org = "https://github.com/Migracode-Barcelona"
repo = "https://github.com/Migracode-Barcelona/curriculum/"
root = "curriculum"
# We use a proxy which concatenates paginated responses, otherwise we miss results.
# Daniel is currently hosting this code https://github.com/illicitonion/github-issue-proxy but we should work out a long-term maintainable solution to this problem.
# The /cached/120 path prefix here caches results for 2 hours to avoid rate limits. Drop the /cached/120 if you need fresh results.
orgapi = "https://github-issue-proxy.illicitonion.com/cached/120/repos/Migracode-Barcelona/"

#on production build though we don't want Hugo to cache - only in dev
[caches.getresource]
maxAge="0"

[security.funcs]
# Allow accessing a GitHub bearer token to avoid rate limits when doing HTTP fetches to the GitHub API.
# This can be generated at https://github.com/settings/tokens?type=beta and needs read-only access to all public CYF GitHub repos.
getenv = ["^HUGO_CURRICULUM_GITHUB_BEARER_TOKEN$"]

[markup]
[markup.tableOfContents]
endLevel = 2
ordered = true
startLevel = 2
[markup.highlight]
lineNos = false
codeFences = true
guessSyntax = true
[markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
unsafe = true
hardWraps = true
disableKinds = ["taxonomy", "term"]
footnote= true

theme = "common-theme"
